const Map<String, String> images = {
  'angelina-front':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/angelina_front.jpg?raw=true',
  'angelina-length':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/angelina_length.jpg?raw=true',
  'barbara-front':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/barbara_front.jpg?raw=true',
  'barbara-length':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/barbara_length.jpg?raw=true',
  'gigi-front':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/gigi_front.jpg?raw=true',
  'gigi-length':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/gigi_length.jpg?raw=true',
  'kendall-front':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/kendall_front.jpg?raw=true',
  'kendall-length':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/kendall_length.jpg?raw=true',
  'zayn-front':
      'https://github.com/arguswaikhom/media_archive/blob/master/assets/images/zayn_front.jpg?raw=true',
};
